channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - jupyter
  - ipykernel
  - pandas=0.24.2
  - numpy=1.16.3
  - seaborn=0.9.0
  - scikit-learn=0.20.3
  - statsmodels=0.9.0
  - pyarrow=0.12.1
  - shap=0.28.5

  - pip:
    - graphviz==0.10.1
